public enum SequenceID {
    None,
    seq_shop,
    seq_skins,
    seq_boosts,
    seq_upgrades,
    seq_orbs,
    seq_rings,
    seq_artifacts,
    seq_museum,
    seq_pvp,
    seq_leaderboard,
    seq_playBtn,
    seq_missions,
    seq_profile,
    seq_quests,
}